services:
  gophers-api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./images/:/home/gophershoney/images/
    networks:
      default:
      internal:

networks:
  default:
  internal:
    internal: true